services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    DfsAbonnements\Controller\Admin\AdminDfsAbonnementsController:
        arguments:
            $orderGridFactory: '@prestashop.core.grid.factory.order'
        tags:
            - { name: controller.service_arguments }

    DfsAbonnements\Controller\Admin\AdminDfsAbonnementsConfigController:
        tags:
            - { name: controller.service_arguments }
